# SwiftLint Configuration File
# For full documentation see: https://realm.github.io/SwiftLint/

# 包含的路径
included:
  - Sources
  - Tests

# 排除的路径
excluded:
  - .build
  - Package.swift
  - .swiftpm

# 启用的规则
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# 禁用的规则
disabled_rules:
  - trailing_comma  # 我们使用 SwiftFormat 来处理尾随逗号
  - explicit_access_control  # 禁用显式访问控制要求
  - trailing_closure  # 禁用尾随闭包语法要求

# 规则配置
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - uri